<<<<<<< HEAD
name: Greeter


on:
  workflow_dispatch:
  push:


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: step 1, Greet
        run: echo hello team!

      - name: step 2
        run: echo bye bye
=======
name: Greeter


on:
  workflow_dispatch:

  push:
  pull_request:



jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: step 1, Greet
        run: echo hello team!


      - name: step 2
        run: echo bye bye
>>>>>>> 8875a4f321ae5d11c71137dc7cb6f94efabf4be8
