name: Greeter


on:
  workflow_dispatch:
  push:


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: step 1, Greet
        run: echo hello team!

      - name: step 2
        run: echo bye bye

